### ISSUE TITLE
Update the way the API URL is discovered

### ISSUE THREAD

**Issue by pmuir** [fabric8-ui/fabric8-recommender#1]
1) Add this file to fabric8-ui/fabric8-recommender https://github.com/fabric8io/fabric8-ui/blob/master/src/app/analyze/stack/recommender-api.ts and remove it from fabric8io/fabric8-ui
2) Use `@Inject(RECOMMENDER_API_URL) apiUrl: string` to inject the api url in to any component, and remove all code that refers to process.env

**Comment by humaton** [comment]
I have cherry-picked your commits from the fabric8-ui to the master branch.
