### ISSUE TITLE
fabric8-stack-analysis-ui cannot locate c3

### ISSUE THREAD

**Issue by dlabrecq** [fabric8-ui/fabric8-recommender#225]
While converting fabric8-ui to use Less, @mindreeper2420 and I encountered a new issue with the webpack build. That is, the build fails to compile while complaining that fabric8-stack-analysis-ui cannot locate c3.

```
ERROR in ./~/fabric8-stack-analysis-ui/src/app/stack/overview/chart-component.js
Module not found: Error: Can't resolve 'c3' in '/Users/dlabrecq/Work/alm/repos/fabric8-ui/node_modules/fabric8-stack-analysis-ui/src/app/stack/overview'
```

I don't see c3 as a dependency in package.json, but chart-component.js appears to require it.

`import * as c3 from 'c3'; <<< Line 7 of chart-component.js`

That said, the work around is to modify webpack to use Patternfly's c3 dependency, like so. However, this is something we should resolve in the fabric8-stack-analysis-ui package instead.

```
resolve: {
...
      modules: [helpers.root('src'), helpers.root('node_modules'),

        // Todo: fabric8-stack-analysis-ui/src/app/stack/overview/chart-component.js cannot locate c3
        helpers.root("node_modules/patternfly/node_modules/c3"),
        helpers.root("node_modules/patternfly/node_modules/d3")
      ]
```

Note the error is reproducible with the Less conversion branch.

https://github.com/mindreeper2420/fabric8-ui/tree/less-conversion

**Comment by jyasveer** [comment]
We are using patternfly-sass-with-css npm package which has c3 as the dependency. 
But for simplicity i have added c3 as a package dependency to the package.json. you can follow the change on this PR https://github.com/fabric8-ui/fabric8-recommender/pull/233

**Comment by joshuawilson** [comment]
@jyasveer we are in the process of converting everything over to LESS so we can use PatternFly natively.

**Comment by jyasveer** [comment]
@dlabrecq okay. i have added c3 as the dependency in package.json for this repo.
