### ISSUE TITLE
Stack Report Recommendations never populates

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-recommender#243]
_From @burrsutter on June 7, 2017 21:30_

https://screencast.com/t/3vK0v13q6p

_Copied from original issue: openshiftio/openshift.io#208_

**Comment by samuzzal-choudhury** [comment]
@jyasveer please check my comments in https://github.com/openshiftio/openshift.io/issues/208. Please coordinate with Muru from the UX team to come up with a UX and implement the UI. This has got a high priority.

**Comment by arunkumars08** [comment]
@jyasveer Please have a look at this and make the necessary changes. https://github.com/fabric8io/fabric8-ui/commit/d5af7826a2bb0600ec626b1d26776f3fb8928167

**Comment by jyasveer** [comment]
@arunkumars08 @samuzzal-choudhury sure. i will take care of this.

**Comment by jyasveer** [comment]
issue is fixed:
https://github.com/fabric8io/fabric8-ui/pull/1513
