### ISSUE TITLE
Stack Report is incomplete for code metrics

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-recommender#245]
_From @christian-posta on June 21, 2017 15:33_

See this image:

<img width="1107" alt="oio-code-metrics" src="https://user-images.githubusercontent.com/53201/27392747-49560204-565c-11e7-86bf-5b79fc4a88de.png">

_Copied from original issue: openshiftio/openshift.io#275_

**Comment by joshuawilson** [comment]
_From @christian-posta on June 21, 2017 15:36_

Here's the code from the git repo used in this project/codebase

https://github.com/christian-posta/basic-springboot

**Comment by samuzzal-choudhury** [comment]
@christian-posta @joshuawilson issue observed as there was no code metrics available in the system for those dependencies.

**Comment by invincibleJai** [comment]
as @samuzzal-choudhury updated there was no code metrics data so it populated with negative values , have opened the issue to handle it in UI layer (https://github.com/fabric8-ui/fabric8-recommender/issues/249) hence this can be closed @arunkumars08 ??

**Comment by arunkumars08** [comment]
@invincibleJai Yes.
