### ISSUE TITLE
In Code Metrics section, lines of code, avg cyclomatic complexity, total files should show as 'NA' if there is no data/-ve values.

### ISSUE THREAD

**Issue by invincibleJai** [fabric8-ui/fabric8-recommender#249]
* In Code Metrics section, lines of code, avg cyclomatic complexity, total files should show as 'NA' if there is no data/-ve values.

**Comment by joshuawilson** [comment]
When this is finished and closed please comment on https://github.com/openshiftio/openshift.io/issues/275

**Comment by invincibleJai** [comment]
@joshuawilson sure Joshua!!
