### ISSUE TITLE
Stack Report Dropdown: Display only the meaningful portion of the manifest file path

### ISSUE THREAD

**Issue by samuzzal-choudhury** [fabric8-ui/fabric8-recommender#258]
In stack report, a dropdown has been introduced that enables users to change reports for different manifest files in a multi-module application. Currently, that dropdown displays the full build path of manifest files that includes unnecessary reference of a temporary build location.

See https://www.screencast.com/t/DTyNN6zia

Please display only the meaningful portion from the application's context in the dropdown. Also, please make sure that this change is verified by the UX team.

CC: @jyasveer

**Comment by jyasveer** [comment]
this is fixed here https://github.com/fabric8-analytics/fabric8-analytics-jenkins-plugin/pull/5
