### ISSUE TITLE
Convert to LESS and add Stylelint

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8-ui/fabric8-recommender#314]
Convert all `.scss` files to `.less` and add Stylelint to check code quality. File structure, configurations and rulesets will be updated to match fabric8-ui.

**Comment by mindreeper2420** [comment]
I'll be taking on this issue, per the request of @joshuawilson. I can't assign this to myself, so if someone wants to assign it to me, that'd be great :-)

**Comment by mindreeper2420** [comment]
@joshuawilson PR filed for conversion work and including Stylelint into the build and test processes.

**Comment by joshuawilson** [comment]
thanks
