### ISSUE TITLE
Creating NPM module

### ISSUE THREAD

**Issue by arunkumars08** [fabric8-ui/fabric8-recommender#51]

**Comment by joshuawilson** [comment]
@arunkumars08 the branch you have removes too much. You should focus on adding / replacing based on fabric8-planner and/or ngx-widgets. If you remove all the things you are taking out you will not be able to build it.

**Comment by arunkumars08** [comment]
@joshuawilson Yes. Joshua I agree. That's one of the reason why I didn't merge it to the master branch.

We have to figure out a way of using things as that is vital for development.

**Comment by invincibleJai** [comment]
@arunkumars08 we can have planner as reference , have sent a mail in morning with steps discussed with Joshua

**Comment by arunkumars08** [comment]
👍

**Comment by arunkumars08** [comment]
Raised a new ticket for the same. Will handle things one by one. https://github.com/fabric8-ui/fabric8-recommender/issues/52
