### ISSUE TITLE
Make the NPM package production ready

### ISSUE THREAD

**Issue by arunkumars08** [fabric8-ui/fabric8-recommender#52]
1. Include all the necessary version upgrades
2. Upgrade webpack.
3. Introduce Release cycles.

**Comment by joshuawilson** [comment]
This is more of a User Story and should be done with multiple commits so that if something goes wrong you can trace it easier.

**Comment by arunkumars08** [comment]
@joshuawilson Sure. Got it. Thanks 👍 Will make sure I have necessary section of commits
